# build environment
FROM --platform=linux/amd64 node:14-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json yarn.lock ./
RUN apk add --no-cache git
RUN yarn install
COPY . ./
RUN yarn run build

# production environment
FROM --platform=linux/amd64 nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
